import { type Locator, type Page } from '@playwright/test';


export class clientListLoc{
    readonly page: Page;
    readonly clientListTab : Locator;
    readonly activeStatusList1 : Locator;
    readonly searchCompanyNameField : Locator;
    readonly searchCompanyNameButton : Locator;
    readonly resultClientListFSFasttrack : Locator;
    readonly resultClientListFSFasttrackLink : Locator;
    readonly clientProfileStatusActive : Locator;
    readonly clientProfileMemberCount : Locator;
    readonly clientProfileMemberCountN : Locator;
    readonly clientMemberDashboardCount : Locator;
    readonly clientTechProfileTab : Locator;
    readonly clientWeeklyFloorReportTab : Locator;
    readonly clientWeeklyFloorAddReportButton : Locator;
    readonly clientCheckpointMeetingTab : Locator;
    readonly clientCheckpointMeetingDashboard : Locator;
    readonly clientPerformanceReviewTab : Locator;
    readonly clientAllReviewDashboard : Locator;
    readonly clientPerformanceReviewDashboard : Locator;
    readonly clientTalentInterviewTab : Locator;
    readonly clientAddInterviewButton : Locator;
    readonly clientTeamRequestTab : Locator;
    readonly clientTeamMemberTab : Locator;
    readonly clientAddTalentButton : Locator;
    readonly clientActiveMembersLabel : Locator;
    readonly clientContactsTab : Locator;
    readonly clientAddContactsButton : Locator;
    readonly clientMSATab : Locator;
    readonly clientUploadSignedDocuButton : Locator;
    readonly clientTechProfileLabel : Locator;
    readonly clientTechStackDashboard : Locator;
    readonly clientTechStackSkillNet : Locator;
    readonly clientProjectTab : Locator;
    readonly clientAddProjectButton : Locator;
    readonly clientProjectListFSFT : Locator;
    readonly clientChangeLogsTab : Locator;
    readonly clientChangeLogsLabelProj : Locator;
    readonly clientChangeLogsCloseButton : Locator;
    readonly clientSettingsTab : Locator;
    readonly clientSettingsDailyFrequency : Locator;
    readonly filterPerformaceReviewSortLatestButton: Locator;
    readonly filterPerformaceReviewSortLatestLink: Locator;
    readonly filterResultPerformaceReviewSortLastDate: Locator;
    readonly filterPerformaceReviewSortEmployeeNameLink: Locator;
    readonly filterPerformaceReviewSortEmployeeNameButton: Locator;
    readonly filterResultPerformaceReviewSortEmployeeBarriga: Locator;
    readonly filterPerformaceReviewSortStatusButton: Locator;
    readonly filterPerformaceReviewSortStatusLink: Locator;
    readonly filterResultPerformaceReviewSortStatusLastDate: Locator;
    readonly filterPerformaceReviewTeamMemberSelector: Locator;
    readonly filterPerformaceReviewTeamMemberBartlett: Locator;
    readonly filterPerformaceReviewTeamMemberData: Locator;
    readonly filterPerformaceReviewTeamMemberAll: Locator;
    readonly filterPerformaceReviewTeamMemberRowgroupBartlett: Locator;
    readonly filterPerformaceReviewTeamMemberRowgroupData: Locator;
    readonly filterPerformaceReviewStatusAllButton: Locator;
    readonly filterPerformaceReviewStatusAllLink: Locator;
    readonly filterPerformaceReviewStatusMRPendingLink: Locator;
    readonly filterPerformaceReviewStatusMRPendingButton: Locator;
    readonly filterPerformaceReviewStatusMDPendingLink: Locator;
    readonly filterPerformaceReviewStatusMDPendingButton: Locator;
    readonly filterPerformaceReviewStatusEAcknowledgementLink: Locator;
    readonly filterPerformaceReviewStatusEAcknowledgementButton: Locator;
    readonly filterPerformaceReviewStatusReviewCompleteLink: Locator;
    readonly filterPerformaceReviewStatusReviewCompleteButton: Locator;
    readonly sortingWeeklyFloorReportDateT: Locator;
    readonly sortingWeeklyFloorReportDateC: Locator;
    readonly sortingWeeklyFloorReportDateJan: Locator;
    readonly sortingTeamMemberEmployeeC: Locator;
    readonly sortingTeamMemberPositionC: Locator;
    readonly sortingTeamMemberClientRatingC: Locator;
    readonly sortingContactsNameC: Locator;
    readonly sortingContactsNameT: Locator;
    readonly sortingContactsNameGridTSR: Locator;
    readonly sortingMSANameC: Locator;
    readonly sortingMSAGridName: Locator;
    readonly sortingMSAStatusC: Locator;
    readonly sortingMSAEDateC: Locator;
    readonly sortingMSAUpdatedC: Locator;
    readonly sortingProjectNameC: Locator;
    readonly sortingDescriptionC: Locator;


    constructor(page: Page){
        this.page = page;
        this.clientListTab = page.getByRole('button', { name: ' Client List' });
        this.activeStatusList1 = page.locator('td:nth-child(3)').first();
        this.searchCompanyNameField = page.getByPlaceholder('Search Company Name');
        this.searchCompanyNameButton = page.getByRole('button', { name: '', exact: true });
        this.resultClientListFSFasttrack = page.getByRole('gridcell', { name: 'Full Scale Fast Track' });
        this.resultClientListFSFasttrackLink = page.getByRole('link', { name: 'Full Scale Fast Track' });
        this.clientListTab = page.getByRole('button', { name: ' Client List' });
        this.activeStatusList1 = page.locator('td:nth-child(3)').first();
        this.searchCompanyNameField = page.getByPlaceholder('Search Company Name');
        this.clientProfileStatusActive = page.locator('span').filter({ hasText: 'Active' }).first();
        this.clientProfileMemberCount = page.getByText('(9)');
        this.clientProfileMemberCountN = page.getByText('9 members');
        this.clientMemberDashboardCount = page.getByText('TEAM MEMBERS (9)')
        this.clientTechProfileTab = page.getByRole('tab', { name: 'Tech Profile' });
        this.clientWeeklyFloorReportTab = page.getByRole('tab', { name: 'Weekly Floor Report' });
        this.clientWeeklyFloorAddReportButton = page.getByText('Add Report');
        this.clientCheckpointMeetingTab = page.getByRole('tab', { name: 'Checkpoint Meetings' });
        this.clientCheckpointMeetingDashboard = page.getByText('CHECKPOINT MEETINGS', { exact: true });
        this.clientPerformanceReviewTab = page.getByRole('tab', { name: 'Performance Reviews' });
        this.clientAllReviewDashboard = page.getByText('All Reviews');
        this.clientPerformanceReviewDashboard = page.getByText('PERFORMANCE REVIEWS', { exact: true });
        this.clientTalentInterviewTab = page.getByRole('tab', { name: 'Talent Interviews' });
        this.clientAddInterviewButton = page.getByRole('link', { name: ' Add Interview' });
        this.clientTeamRequestTab = page.getByRole('tab', { name: 'Team Requests' });
        this.clientTeamMemberTab = page.getByRole('tab', { name: 'Team Members' });
        this.clientAddTalentButton = page.getByRole('button', { name: ' Add Talent' });
        this.clientActiveMembersLabel = page.getByText('Active Members');
        this.clientContactsTab = page.getByRole('tab', { name: 'Contacts' });
        this.clientAddContactsButton = page.getByText('Add Contact');
        this.clientMSATab = page.getByRole('tab', { name: 'MSA' });
        this.clientUploadSignedDocuButton = page.getByText('Upload Signed Document');
        this.clientTechProfileLabel = page.getByRole('heading', { name: 'Technical Profile' });
        this.clientTechStackDashboard = page.getByText('Tech Stack', { exact: true });
        this.clientTechStackSkillNet = page.locator('#nav-tech-profile').getByText('.NET Core');
        this.clientProjectTab = page.getByRole('tab', { name: 'Projects' });
        this.clientAddProjectButton = page.getByText('Add Project');
        this.clientProjectListFSFT = page.locator('#project-table').getByText('Full Scale Fast Track');
        this.clientChangeLogsTab = page.getByRole('tab', { name: 'Change Logs' });
        this.clientChangeLogsLabelProj = page.getByRole('heading', { name: 'Client Change Log: Full Scale' });
        this.clientChangeLogsCloseButton = page.getByRole('button', { name: 'Press Esc to close' });
        this.clientSettingsTab = page.getByRole('tab', { name: 'Settings' });
        this.clientSettingsDailyFrequency = page.getByText('Daily Report Frequency:');
        this.filterPerformaceReviewSortLatestButton = page.getByRole('button', { name: 'Latest ' }); 
        this.filterPerformaceReviewSortLatestLink = page.getByRole('link', { name: 'Latest' }); 
        this.filterResultPerformaceReviewSortLastDate = page.getByRole('rowgroup').filter({ hasText: 'January 01, 2025 - March 31, 2025' });
        this.filterPerformaceReviewSortEmployeeNameLink = page.getByRole('link', { name: 'Employee Name' });
        this.filterPerformaceReviewSortEmployeeNameButton = page.getByRole('button', { name: 'Employee Name' });
        this.filterResultPerformaceReviewSortEmployeeBarriga = page.getByText('Barriga, Horeb Mendez Developer').first();
        this.filterPerformaceReviewSortStatusButton = page.getByRole('button', { name: 'Status ', exact: true });
        this.filterPerformaceReviewSortStatusLink = page.getByRole('link', { name: 'Status', exact: true });
        this.filterResultPerformaceReviewSortStatusLastDate = page.getByText('Developer ● Quarter April 01, 2024 - June 30, 2024', { exact: true }).first();
        this.filterPerformaceReviewTeamMemberSelector = page.locator('.multiselect__select').first();
        this.filterPerformaceReviewTeamMemberBartlett = page.getByText('Bartlett, Edwin').first();
        this.filterPerformaceReviewTeamMemberData = page.getByText('Data, Lirae Que').first();
        this.filterPerformaceReviewTeamMemberRowgroupBartlett = page.getByRole('rowgroup').filter({ hasText: 'Bartlett, Edwin' });
        this.filterPerformaceReviewTeamMemberRowgroupData = page.getByRole('rowgroup').filter({ hasText: 'Data, Lirae Que Astorga' });
        this.filterPerformaceReviewTeamMemberAll = page.locator('span').filter({ hasText: 'All' }).first();
        this.filterPerformaceReviewStatusAllButton = page.getByRole('button', { name: 'All ' });
        this.filterPerformaceReviewStatusAllLink = page.getByRole('link', { name: 'All' });
        this.filterPerformaceReviewStatusMRPendingLink = page.getByRole('link', { name: 'Manager Review Pending' });
        this.filterPerformaceReviewStatusMRPendingButton = page.getByRole('button', { name: 'Manager Review Pending ' });
        this.filterPerformaceReviewStatusMDPendingLink = page.getByRole('link', { name: 'Manager Discussion Pending' });
        this.filterPerformaceReviewStatusMDPendingButton = page.getByRole('button', { name: 'Manager Discussion Pending ' });
        this.filterPerformaceReviewStatusEAcknowledgementLink = page.getByRole('link', { name: 'Employee Acknowledgment' });
        this.filterPerformaceReviewStatusEAcknowledgementButton = page.getByRole('button', { name: 'Employee Acknowledgment' })
        this.filterPerformaceReviewStatusReviewCompleteLink = page.getByRole('link', { name: 'Review Complete' });
        this.filterPerformaceReviewStatusReviewCompleteButton = page.getByRole('button', { name: 'Review Complete ' }); 
        this.sortingWeeklyFloorReportDateT = page.getByRole('table').getByText('Date');
        this.sortingWeeklyFloorReportDateC = page.getByRole('cell', { name: 'Date ↑ ↓' });
        this.sortingWeeklyFloorReportDateJan = page.getByText('Jan 17,');
        this.sortingTeamMemberEmployeeC = page.getByRole('cell', { name: 'Employee ↑ ↓' }).first();
        this.sortingTeamMemberPositionC = page.locator('th:nth-child(3) > .col-md-auto').first();
        this.sortingTeamMemberClientRatingC = page.getByRole('cell', { name: 'Recent Client Rating ↑ ↓' }).locator('div').first();
        this.sortingContactsNameC = page.getByRole('cell', { name: 'Name ↑ ↓' });
        this.sortingContactsNameT = page.getByRole('table').getByText('Name');
        this.sortingContactsNameGridTSR = page.getByRole('gridcell', { name: 'Test Sean Ray' });
        this.sortingMSANameC = page.getByRole('cell', { name: 'Name ↑ ↓' });
        this.sortingMSAGridName = page.getByRole('gridcell', { name: 'Master Service Agreement' });
        this.sortingMSAStatusC = page.getByRole('cell', { name: 'Status ↑ ↓' });
        this.sortingMSAEDateC = page.getByRole('cell', { name: 'Effective Date ↑ ↓' });
        this.sortingMSAUpdatedC = page.getByRole('cell', { name: 'Updated ↑ ↓' });
        this.sortingProjectNameC = page.getByRole('cell', { name: 'Project Name ↑ ↓' });
        this.sortingDescriptionC = page.getByRole('cell', { name: 'Description ↑ ↓' });
    }

}
