module.exports = {
    clientContactsTab : "//a[contains(text(),'Contacts')]",
    addContactBtn : "//a[contains(text(),'Add Contact')]",
    contactName : "//input[@id='text-name']",
    contactEmail : "//div[@class='email-field']//input",
    enableLoginToggle : "//input[@name='form-checkbox-can_login']/following-sibling::label",
    saveContact : "//span[text()='Save Contact']",
    contactEmailColumnList : "//td[@class='email-column'] | //td[@class='mobile-layout']//span[2]",
    trimmedContactEmailColumnList : "//td[@class='email-column']/text()[normalize-space()]",
    contactSavedNotification : "Contact has been saved successfully",
    contactActionColumnList : "//button[contains(@id,'fsButtonDropdown-contact')]",
    contactDeleteList : "//i[contains(@class,'la-trash')]",
    dashboard : "//h2[text()='Dashboard']",
    maleAvatar : "//img[contains(@src,'/male.png')]",
    eventsHoliday : "//div[contains(text(),'Events and Holidays (PH)')]",
    clientPass : "//input[@id='pass1']",
    clientConfirmPass : "//input[@id='pass2']",
    clientSignIn : "//button[@id='changePassBtn']",
    teamRequestsTab : "//a[contains(text(),'Team Requests')]",
    searchRequest : "//div[contains(@class,'search-wrapper')]//input",
    requestEmployeeName : "//table[@id='team-request-datatable']/tbody/tr//div[contains(@class,'media-body')]//a[contains(@href,'profile')]",
    requestStatus : "//div[contains(@class,'action-dropdowns')]/div[@title='Change Status']/button[1]",
    teamRequestSideTab : "(//span[contains(text(),'Team Requests')])[1]",
    searchByTalentFld : "//input[@placeholder='Search by talent']",
    teamRequestListName : "//a[contains(@class,'photo-card-user-names')]/div",
    teamRequestListStatus : "//p[text()='Status']/following-sibling::a",
    actionButton : "//button[contains(@id,'fsButtonDropdown-request')]",
    deleteRequest : "//a[contains(text(),'Delete')]",
    confirmDeletion : "//div[contains(@class,'swal2-actions')]/button[text()='Yes']",
    deletionProgress : "//div[contains(text(),'Deleting')]",
    paginationNextPage : "//a[contains(@title,'Go to the next page')]",
    disabledNextPage : "//a[contains(@title,'Go to the next page')]/parent::li[contains(@class,'disabled')]",
    loadingRecords : "//span[contains(text(),'Loading records')]",
    showDropdown : "//span[text()='Show']/following-sibling::span",
    showHundred : "//li[text()='100']",


    clientTopDropdown : "//*[@id='main-wrapper']/nav/div[2]/nav/div[2]/div/a",
    clientLogout : "//span[contains(text(),'Logout')]",

    //Client Portal Dashboard
    tooltip : "//div[@class='tooltip-inner']",
    myProfile : "//span[text()='My Profile']",
    myContacts : "//span[text()='My Contacts']",
    findTalent : "//span[text()='Find Talent']",
    docsandAgreements : "//span[text()='Documents & Agreements']",
    manageTeam : "//span[text()='Manage Team']",
    performanceReview : "//span[text()='Performance Review']",
    reporting : "//span[text()='Reporting']",
    dailyStatusReport : "//span[text()='Daily Status Reports']",
    dailyTimeClockReport : "//span[text()='Daily Time Clock Reports']",
    weeklyTimeClockReport : "//span[text()='Weekly Time Clock Reports']",
    timeClockSummaryReport : "//span[text()='Time Clock Summary Reports']",
    needHelp : "//h4[contains(text(),'Need Help')]",

    //Client Pages
    clientPagesName : "//span[@class='text-underline-hover']",
    technicalProfile : "//span[text()='Technical Profile']",
    homePageButton : "//a[@title='Go to homepage']",
    myContactsHeader : "//h4[text()='My Contacts']",
    findTalentHeader : "//h4[text()='Find Talent']",
    clientDocumentsAgreementsHeader : "//h4[text()='Client Documents & Agreements']",
    manageTeamHeader : "//h4[text()='Manage Team']",
    performanceReviewHeader : "//h4[text()='Performance Evaluation']",
    dailyStatusReportHeader : "//div[text()='DAILY STATUS REPORTS']",
    dailyTimeClockReportHeader : "//div[text()='Daily Time Clock Reports']",
    weeklyTimeReportHeader : "//div[text()='Weekly Time Clock Reports']",
    timeClockSummaryHeader : "//div[text()='Time Clock Summary Reports']",
    talentCount : "//p[contains(text(),'We found')]/strong",
    findAddTalentBtn : "//span[text()='Find and Add Talent']",
    manageTeamBtn : "//a[@title='Manage Team']",
    noMoreRecords : "//div[text()='No more records']",
    nameList : "//a[contains(@class,'photo-card-user-name')]/div",
    firstTalent : "(//span[text()='VIEW PROFILE'])[1]",
    firstActualTalent : "(//div[contains(@class,'talent-info')]//img[not(contains(@src,'coming-soon.png'))]/ancestor::div[contains(@class,'profile-card')]/div[contains(@class,'card-footer')]//div[contains(text(),'Now')]/ancestor::div[contains(@class,'resource-availability')]/following-sibling::a/span[text()='VIEW PROFILE'])[1]",
    saveSelectedProfile : "(//a[@title='Click to save'])[1]",
    bookaCall: "//span[text()='Book a Call']/parent::a",
    addToTeam : "//span[text()='Add to team']/parent::a",
    heartBtn : "//div[@class='talent-favorite']/a",
    saveTalent : "(//i[contains(@class,'heart')])[1]",
    closeModal : "//a[@title='Close']",

    //Reports
    dailyDate : "//span[contains(@class,'la-angle-down')]/preceding-sibling::span",
    timeClockDate : "//td[@class='date'][1]/div",
    latestTimeClockDate : "(//td[@class='date'][1]/div)[1]",
    latestTimeIn : "(//td[@data-title='Time In:'][1]/div)[1]",
    latestTimeOut : "(//td[@data-title='Time Out:'][1]/div)[1]",
    weeklyTimeDates : "//h4[@class='ks-text accordion-title']",
    noReportsAvailable : "//div[contains(@class,'no-records')]",
    monthField : "(//span[contains(@class,'selection')])[1]",
    monthSelection: "//li[contains(@class,'select2-results__option--highlighted')]/preceding-sibling::li[1]",
    latestWeeklyTimeDate : "(//h4[@class='ks-text accordion-title'])[1]",
    employeeNameList : "//div[contains(@class,'weekly-container')][1]//td[text()='Employee Name']/ancestor::table/tbody/tr",
    exportCurrentRecordReportBtn: "//button[text()='Export current records']",
    csvBtn : "//span[text()='CSV']",
    xlsxBtn : "//span[text()='XLSX']",
    exportBtn : "//div[contains(@class,'list-group-item')]//button[contains(text(),'Export')]",
}