module.exports = {
    clientContactsTab : "//a[contains(text(),'Contacts')]",
    addContactBtn : "//span[text()='Add Contact']",
    contactName : "//input[@id='text-name']",
    contactEmail : "//div[@class='email-field']//input",
    enableLoginToggle : "//input[@name='form-checkbox-can_login']/following-sibling::label",
    saveContact : "//button[contains(text(),'SAVE')]",
    contactEmailColumnList : "//td[@class='email-column']",
    trimmedContactEmailColumnList : "//td[@class='email-column']/text()[normalize-space()]",
    contactActionColumnList : "//button[contains(@id,'fsButtonDropdown-contact')]",
    contactDeleteList : "//a[contains(text(),'Delete')]",
    dashboard : "//h2[text()='Dashboard']",
    clientPass : "//input[@id='pass1']",
    clientConfirmPass : "//input[@id='pass2']",
    clientSignIn : "//button[@id='changePassBtn']",
    teamRequestsTab : "//a[contains(text(),'Team Requests')]",
    searchRequest : "//div[contains(@class,'search-wrapper')]//input",
    requestEmployeeName : "//table[@id='team-request-datatable']/tbody/tr//div[contains(@class,'media-body')]//a[contains(@href,'profile')]",
    requestStatus : "//div[contains(@class,'action-dropdowns')]/div[@title='Change Status']/button[1]",
    teamRequestSideTab : "(//span[contains(text(),'Team Requests')])[1]",
    searchByTalentFld : "//input[@placeholder='Search by talent']",
    teamRequestListName : "//a[contains(@class,'photo-card-user-names')]/div",
    teamRequestListStatus : "//p[text()='Status']/following-sibling::a",
    actionButton : "//button[contains(@id,'fsButtonDropdown-request')]",
    deleteRequest : "//a[contains(text(),'Delete')]",
    confirmDeletion : "//div[contains(@class,'swal2-actions')]/button[text()='Yes']",
    deletionProgress : "//div[contains(text(),'Deleting')]",
    paginationNextPage : "//a[contains(@title,'Go to the next page')]",
    disabledNextPage : "//a[contains(@title,'Go to the next page')]/parent::li[contains(@class,'disabled')]",
    loadingRecords : "//span[contains(text(),'Loading records')]",
    showDropdown : "//span[text()='Show']/following-sibling::span",
    showHundred : "//li[text()='100']",
}