module.exports = {

    // Feedback Listing locators
    feedbackResponsesHeader : '//*[@id="fs-page-holder-container"]/div/div[1]/div[1]/div/div[1]/h4',
    topRow : '//*[@id="feedback-list"]/div/div/div/div[2]/div/table/tbody/tr[1]',
    feedbackDetailsBtn : '//*[@id="feedback-list"]/div/div/div/div[2]/div/table/tbody/tr[1]/td[5]/a',
    feedbackResponseModalHeading : '//*[@id="modalTitle"]/h4',
    imageInModal : '//*[@id="feedback-detail-modal-container"]/div/table/tbody/tr[3]/td[2]/div/img',
    closeButton : '//*[@id="modalTitle"]/div/button',

    // Employee List locators
    employeeTable : "//table[@class='table dataTable showHeaderOnly']",
    employeeListHeader : "//h4[contains(text(), 'Employees')]",
    employeeNameLink : "//a[contains(@class,'photo-card-user-names')]",
    addNewEmployeeButton : "//span[text()='Add New Employee']",
    startDate : "//label[contains(text(),'Start Date')]/following-sibling::input[2]",
    dateToday: "//span[@class='flatpickr-day today']",
    firstNameField : "//input[@name='first_name']",
    lastNameField : "//input[@name='last_name']",
    createEmployeeBtn : "//span[text()='Create Employee']",
    employeeListTab : "//span[text()='Employee List']",
    employeeNameList : "//a[contains(@class,'photo-card-user-names')]//span",
    searchEmployee : "//input[contains(@placeholder,'Search Employee')]",
    searchEmployeeBtn : "//button[contains(@class,'btn-search')]",
    editEmployeeClients : "//span[text()='Clients']/following-sibling::a",
    enterProjectField : "//input[@id='projectsSelection']",
    itemSearchSuggestion : "//li[contains(@class,'item valid')]/div",
    saveProject : "//span[text()='Save']",
    clientList : "//span[contains(@class,'tag-name')]",
    manageProjectTitle : "//h4[text()='Manage Project']",

    editSkills : "//div[contains(@class,'skills-and-proficiencies')]/div/a",
    enterSkillField : "//input[@id='skills-selection']",
    skillsList : "//div[@id='skill']//div[contains(@class,'draggable-row')]/div[2]/span",
    showInProfileCheckbox : "//div[@id='skill']//div[contains(@class,'draggable-row')]/div[6]//input",
    searchbleCheckbox : "//div[@id='skill']//div[contains(@class,'draggable-row')]/div[7]//input",
    saveSkills : "//section[@class='modal-footer-new']//span[text()='Save']",
    skillsListInProfile : "//div[contains(@class,'skills-and-proficiencies')]//div/div[1]/span",

    employmentTab : "//span[text()='Employment']",
    editWorkDetail : "//div[@data-original-title='Edit work detail']",
    currentPositionField : "//span[@id='select2-position-level-container']",
    seniorOption : "//li[text()='Senior']",
    positionField : "//input[@id='employee-position']",
    savePosition : "//span[text()='Save']/parent::button",
    currentPosition : "//span[text()='Current Position']/parent::div/parent::div/following-sibling::div/span",
    talentProfileTab : "//span[text()='Talent Profile']",
    modalTitle : "//h4[text()='Work Detail']",
    selectedPosition : "//li[@class='tag valid']",
    selectDeveloperType : "//span[@id='select2-position-subtype-container']",
    fullStackOption : "//li[text()='Full Stack']",
    employeeActionButton : "//button[contains(@id,'fsButtonDropdown-action')]",
    deleteRequest : "//a[contains(text(),'Delete')]",
    confirmDeletion : "//div[contains(@class,'swal2-actions')]/button[text()='Yes']",
    deletionProgress : "//div[contains(text(),'Wait while saving changes')]",
    loadingRecords : "//span[contains(text(),'Loading records')]",
}