module.exports = {
    dashboard : "//h2[text()='Dashboard']",
    myTeam : "//h4[text()='My Team']",
    eventsHoliday : "//div[contains(text(),'Events and Holidays')]",
    savedSuggestedTalent : "//h4[contains(text(),'Saved & Suggested Talent')]",
    myProfileButton : "//span[text()='My Profile']",
    myContactButton : "//span[text()='My Contacts']",
    findTalentButton : "//span[text()='Find Talent']",
    documentsAgreementButton : "//span[text()='Documents & Agreements']",
    manageTeamButton : "//span[text()='Manage Team']",
    reportingButton : "//span[text()='Reporting']",
    needHelpButton : "//h4[contains(text(),'Need Help')]",
    profileDropdown : "//div[contains(@class,'nav-item dropdown')]/a",
    changeTimeZone : "//span[text()='Change Timezone']",
    timeZoneSelection : "//section[@id='modalDescription']//span[@class='selection']",
    setTimeZoneButton : "//span[text()='Set']/parent::button",
    closeTimeZoneModal : "//button[contains(@class,'btn-close')]",
    timeZoneField : "//section[@id='modalDescription']//span[@class='selection']//span[contains(@id,'select2-timezone')]",
    
}