module.exports = {
    myContacts : "//h4[text()='My Contacts']",
    nameHeader : "(//table//div[text()='Name'])[1]",
    emailHeader : "(//table//div[text()='Email'])[1]",
    contactNumberHeader : "(//table//div[text()='Contact Number'])[1]",
    enableLoginHeader : "(//table//div[text()='Enable Login'])[1]",
    accessLevelHeader : "(//table//div[text()='Access Level'])[1]",
    actionHeader: "(//table//div[text()='Action'])[1]",
    addContact : "//span[text()='Add Contact']",
    addContactHeader: "//section[@id='modalDescription']/h4[text()='Add Contact']",
    nameField: "//span[text()='Name']/parent::label/following-sibling::div/input",
    emailField : "//span[text()='Email']/parent::label/following-sibling::div/input",
    contactField : "//label[text()='Contact Number']/parent::span/following-sibling::div/div[2]//input",
    cancelContactButton : "//button[contains(text(),'CANCEL')]",
    contactsPagination : "//a[contains(@class,'page-link') and not(*)]",
    nameList : "//p[text()='Name']/parent::td",
    saveContactButton : "//button[contains(text(),'SAVE')]",
    contactSaveMsg : "//h2[contains(text(),'Contact has been saved successfully')]",
    paginationNextPage : "//a[contains(@title,'Go to the next page')]",
}