module.exports = {
    superAdminAvatar : "//div[@class='nav-item dropdown ks-user']",
    chart : "//div[contains(@id,'apexchart')]",
    selectMyProfileOption : "//span[text()='My Profile']",
    profileName : "//span[contains(@class, 'talent-name')]",
    profileStatus : "//div[contains(@class, 'status-alert--success')]",
    talentPosition : "//span[contains(@class, 'talent-position')]",
    talentPositionIcon : "//i[@class='pr-1 font-16 text-forest-green las la-clipboard-check']",
    yearsOfExperience : "//div[@class='years-of-experience']",
    yearsOfExperienceIcon : "//i[@class='pr-2 font-18 la la-laptop position-relative top-0.5']",
    addTeamManager : "//div[@class='d-flex align-items-start employee-managers']",
    addTeamManagerIcon : "//i[contains(@class,'la-user-tie')]",
    publicProfile : "//a[contains(text(),'Public Profile')]",
    publicProfileEnable : "//a[@class='text-forest-green']",
    publicLinkIcon : "//i[contains(@class,'la-link')]",
    copyClipBoard : "//a[@title='Click to copy URL to clipboard']",
    clientsPlusEdit : "//span[text()='Clients']//parent::h2",
    clientsEditIcon : "//span[text()='Clients']/following-sibling::a",
    clientInterviewsAndIcon : "//span[text()='Client Interviews']//parent::h2",
    clientInterviewsIcon : "//div[@class='d-flex align-items-center gap-1']",
    checkPointMeetings : "//h2[contains(@class,'summary__heading')]/span[text()='Checkpoint Meetings']",
    performanceReviews : "//h2[contains(@class,'summary__heading')]/span[text()='Performance Reviews']",
    skillsAndProficiencies : "//span[contains(text(), 'Skills & Proficiencies')]//parent::h2",
    skillsAndProfEditIcon : "//span[text()='Skills & Proficiencies']//parent::h2//a[contains(@class,'text-forest-green')]",
    talentProfileTab : "//a[@id='nav-talent-profile-link']",
    clientsTab : "//a[@id='nav-clients-link']",
    clientInterviewsTab : "//a[@id='nav-client-interviews-link']",
    checkpointMeetingsTab : "//a[@id='nav-checkpoint-meetings-link']",
    performanceInterviewsTab : "//a[@id='nav-performance-reviews-link']",
    personalTab : "//a[@id='nav-personal-link']",
    employmentTab : "//a[@id='nav-employment-link']",
    changeLogTab : "//a[@id='nav-change-log-link']",
    applicantAssessmentNotes : "//a[@id='nav-applicant-assessment-notes-link']",
    myProfileTabs : "//nav[contains(@class,'sidebar-menu')]//a[@role='tab']/span",
    myHeaderElements : "//h2[contains(@class,'summary__heading')]/span",
    talentProfileEditIcons : "//a[contains(@class,'fs-btn__borderless--orange')]",
    clientSpotLightSelectIcon : "//a[contains(@class,'fs-btn__borderless--green')]",
    applicantAssessmentNotes : "//a[@id='nav-applicant-assessment-notes-link']",
    filesAndAssets : "//div[contains(text(),'Files and Assets')]",
    clientsTabEditIcon : "//a[@type='button']",
    clientsNameLinks: "//div[contains(@class,'text-wrap')]//a",
    clientSalesDashboard : "(//a[contains(text(),'Client / Sales Dashboard')])[1]",
}
