module.exports = {
    searchUser : "//div[contains(@class,'show-search-section')]//input[@id='autosuggest__input']",
    assignRole : "//i[contains(@class,'la-cube')]",
    userRoles : "//ul[contains(@class,'user-role')]/li/span",
    userRolesToggle : "//ul[contains(@class,'user-role')]/li/span/following-sibling::label",
    userRoleOnToggle : "//ul[contains(@class,'user-role')]//span[@class='ks-on']",
    loadingRecords : "//span[contains(text(),'Loading records')]",
    loadingBg : "//div[@class='datatable-mask']",
    currentRole : "//span[@class='fs-active-user']",

    //skills
    skillsTab : "(//span[text()='Skills'])[1]",
    addNewSkillsBtn : "//button[text()='Add New Skills']",
    skillName : "//input[@name='name']",
    addNewSkillSave : "//span[text()='Add New Skill']",
    searchSkill : "//input[@id='autosuggest__input']",
    skillNameList : "//table/tbody/tr/td[1]",
    deleteSkillList : "//i[contains(@class,'la-trash-alt')]",
    confirmDelete : "//button[contains(@class,'swal2-confirm')]",
    paginationNextPage : "//a[contains(@title,'Go to the next page')]",
    skillTaken : "//span[text()='The name has already been taken.']",

    //Process Workflow
    workFlowName : "//td[contains(@class,'action-buttons')]/following-sibling::td[1]/span[2]",
    workFlowActionButton : "//button[contains(@id,'fsButtonDropdown-workflow')]",
    editWorkFlow : "//button[contains(@id,'fsButtonDropdown-workflow')]/following-sibling::div/a",
    templateUpdated : "//h2[text()='Template updated']",
    clientEnableAccessDropdown : "//span[text()='Client Enable Access - Client']/ancestor::tr/td/div/button[contains(@id,'fsButtonDropdown')]",
    clientEnableAccessEditWorkFlow : "//span[text()='Client Enable Access - Client']/ancestor::tr/td/div/div/a",
    emailToField : "//input[@id='text-datalist-email_to']",
    saveWorkFlow : "//span[text()='Save']/parent::a",
    savingChanges : "//div[contains(text(),'Saving changes')]",

    //Expense Report Settings
    tableMask : "//div[@class='datatable-mask']",
    searchExpenseId : "//input[contains(@placeholder,'Search by Expense Report ID')]",
    expenseId : "//p[text()='Expense ID']/following-sibling::span[1]",
    loadingOverlay : "//div[@class='loadingoverlay']",
    expenseReportTab : "(//span[text()='Expense Report'])[1]",
    editGeneralSetting : "//legend[text()='General Settings']/following-sibling::div//a",
    expenseReportRecipientField : "//div[contains(text(),'Admin Email Recipients')]/following-sibling::div//div[@class='fs-tags-input']/input",
    expenseReportRecipient : "//div[contains(text(),'Admin Email Recipients')]/following-sibling::div//span[contains(@class,'fs-tags-input-badge')]/span",
    removeExpenseReportRecipient : "//div[contains(text(),'Admin Email Recipients')]/following-sibling::div//span[contains(@class,'fs-tags-input-badge')]/i",
    saveGeneralSettings : "//a[contains(text(),'Save')]",
    expenseReportsTab : "(//span[text()='Expense Reports'])[1]",
}